apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVlTRTROWENCSUUyQjRaNFQ=
  AWS_SECRET_ACCESS_KEY: V0RhMjJlYWpaODhqNllYbHNRSGQvcXR3ai9nb2xFa010STh5RDN6UQ==
